[package]
name = "main_project"
version = "0.1.0"
edition = "2021"

[profile.release]
debug = true

[dependencies]
chess_uci = { path = "../chess_uci" }
chess_core = { path = "../chess_core" }

rayon = "1.5"

rand = "0.8.5"
